### Importing libraries

In [1]:
import pandas as pd
import numpy as np

# featuretools for automated feature engineering
#import featuretools as ft

# matplotlib and seaborn for visualizations
import matplotlib.pyplot as plt
plt.rcParams['font.size'] = 22
import seaborn as sns

# Suppress warnings from pandas
import warnings
warnings.filterwarnings('ignore')

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_selection import SelectKBest 
from sklearn.feature_selection import chi2
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

import tensorflow as tf
from tensorflow import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers.normalization import BatchNormalization

Using TensorFlow backend.

### Fetching final merged file

In [2]:
app_train = pd.read_csv('train_final.csv').sort_values('SK_ID_CURR').reset_index(drop = True)

In [3]:
app_train

,Unnamed: 0,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,client_installments_AMT_PAYMENT_min_sum,client_installments_AMT_INSTALMENT_min_sum,client_installments_AMT_PAYMENT_sum_max,client_installments_AMT_INSTALMENT_sum_max,client_installments_AMT_PAYMENT_mean_sum,client_installments_AMT_INSTALMENT_mean_sum,client_installments_AMT_INSTALMENT_max_sum,client_installments_AMT_PAYMENT_max_sum,client_installments_AMT_PAYMENT_sum_sum,client_installments_AMT_INSTALMENT_sum_sum
0,0,100002,1,0,0,1,0,202500.0,406597.5,24700.5,...,175783.73,175783.73,219625.700,219625.700,219625.690,219625.690,1.008781e+06,1.008781e+06,4.172888e+06,4.172888e+06
1,1,100003,0,0,0,0,0,270000.0,1293502.5,35698.5,...,1154108.20,1154108.20,1150977.400,1150977.400,1618864.600,1618864.600,4.394102e+06,4.394102e+06,1.134881e+07,1.134881e+07
2,2,100004,0,1,1,1,0,67500.0,135000.0,6750.0,...,16071.75,16071.75,21288.465,21288.465,21288.465,21288.465,3.172190e+04,3.172190e+04,6.386539e+04,6.386539e+04
3,3,100006,0,0,0,1,0,135000.0,312682.5,29686.5,...,994476.70,994476.70,691786.900,691786.900,1007153.400,1007153.400,1.057860e+06,1.057860e+06,3.719995e+06,3.719995e+06
4,4,100007,0,0,0,1,0,121500.0,513000.0,21865.5,...,483756.38,825845.80,280199.700,294631.120,806127.940,835985.300,8.367034e+05,8.367034e+05,1.139621e+07,1.179154e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,307506,456251,0,0,0,0,0,157500.0,254700.0,27558.0,...,46241.37,46241.37,52450.470,52450.470,52450.470,52450.470,8.970507e+04,8.970507e+04,3.671533e+05,3.671533e+05
307507,307507,456252,0,0,0,1,0,72000.0,269550.0,12001.5,...,60281.28,60281.28,60419.203,60419.203,60419.203,60419.203,6.044679e+04,6.044679e+04,3.625152e+05,3.625152e+05
307508,307508,456253,0,0,0,1,0,153000.0,677664.0,29979.0,...,41805.99,61529.04,33413.758,33413.758,57622.812,61595.910,6.166175e+04,6.166175e+04,3.048920e+05,3.247575e+05
307509,307509,456254,1,0,0,1,0,171000.0,370107.0,20205.0,...,194556.81,194556.81,171592.420,171592.420,194556.810,194556.810,1.945568e+05,1.945568e+05,1.773976e+06,1.773976e+06
307510,307510,456255,0,0,0,0,0,157500.0,675000.0,49117.5,...,171612.27,1646200.60,2251553.800,1692260.900,3525819.800,3068388.800,2.415755e+07,2.572420e+07,8.135078e+07,6.643655e+07

In [4]:
# Independent variable
x=app_train.drop(columns = ['TARGET','Unnamed: 0'])

In [5]:
x

,SK_ID_CURR,NAME_CONTRACT_TYPE,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,...,client_installments_AMT_PAYMENT_min_sum,client_installments_AMT_INSTALMENT_min_sum,client_installments_AMT_PAYMENT_sum_max,client_installments_AMT_INSTALMENT_sum_max,client_installments_AMT_PAYMENT_mean_sum,client_installments_AMT_INSTALMENT_mean_sum,client_installments_AMT_INSTALMENT_max_sum,client_installments_AMT_PAYMENT_max_sum,client_installments_AMT_PAYMENT_sum_sum,client_installments_AMT_INSTALMENT_sum_sum
0,100002,0,0,1,0,202500.0,406597.5,24700.5,351000.0,0.018801,...,175783.73,175783.73,219625.700,219625.700,219625.690,219625.690,1.008781e+06,1.008781e+06,4.172888e+06,4.172888e+06
1,100003,0,0,0,0,270000.0,1293502.5,35698.5,1129500.0,0.003541,...,1154108.20,1154108.20,1150977.400,1150977.400,1618864.600,1618864.600,4.394102e+06,4.394102e+06,1.134881e+07,1.134881e+07
2,100004,1,1,1,0,67500.0,135000.0,6750.0,135000.0,0.010032,...,16071.75,16071.75,21288.465,21288.465,21288.465,21288.465,3.172190e+04,3.172190e+04,6.386539e+04,6.386539e+04
3,100006,0,0,1,0,135000.0,312682.5,29686.5,297000.0,0.008019,...,994476.70,994476.70,691786.900,691786.900,1007153.400,1007153.400,1.057860e+06,1.057860e+06,3.719995e+06,3.719995e+06
4,100007,0,0,1,0,121500.0,513000.0,21865.5,513000.0,0.028663,...,483756.38,825845.80,280199.700,294631.120,806127.940,835985.300,8.367034e+05,8.367034e+05,1.139621e+07,1.179154e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
307506,456251,0,0,0,0,157500.0,254700.0,27558.0,225000.0,0.032561,...,46241.37,46241.37,52450.470,52450.470,52450.470,52450.470,8.970507e+04,8.970507e+04,3.671533e+05,3.671533e+05
307507,456252,0,0,1,0,72000.0,269550.0,12001.5,225000.0,0.025164,...,60281.28,60281.28,60419.203,60419.203,60419.203,60419.203,6.044679e+04,6.044679e+04,3.625152e+05,3.625152e+05
307508,456253,0,0,1,0,153000.0,677664.0,29979.0,585000.0,0.005002,...,41805.99,61529.04,33413.758,33413.758,57622.812,61595.910,6.166175e+04,6.166175e+04,3.048920e+05,3.247575e+05
307509,456254,0,0,1,0,171000.0,370107.0,20205.0,319500.0,0.005313,...,194556.81,194556.81,171592.420,171592.420,194556.810,194556.810,1.945568e+05,1.945568e+05,1.773976e+06,1.773976e+06
307510,456255,0,0,0,0,157500.0,675000.0,49117.5,675000.0,0.046220,...,171612.27,1646200.60,2251553.800,1692260.900,3525819.800,3068388.800,2.415755e+07,2.572420e+07,8.135078e+07,6.643655e+07

In [6]:
# Dependent variable
y=app_train.iloc[:,2].values

In [7]:
y

array([1, 0, 0, ..., 0, 1, 0], dtype=int64)

In [8]:
# Function to check missing values
def missing_values_table(df):
    mis_val=df.isnull().sum()
    mis_val_percent=100*mis_val/len(df)
    mis_val_table=pd.concat([mis_val,mis_val_percent],axis=1)
    mis_val_table_ren_columns=mis_val_table.rename(columns={0:'Missing values',1:'% of Total_values'})
    mis_val_table_ren_columns=mis_val_table_ren_columns[mis_val_table_ren_columns.iloc[:,1]!=0].sort_values('% of Total_values',ascending=False).round(1)
    return mis_val_table_ren_columns

In [9]:
missing_x=missing_values_table(x)
missing_x

                                       Missing values  % of Total_values
previous_RATE_INTEREST_PRIVILEGED_max          302902               98.5
previous_RATE_INTEREST_PRIMARY_min             302902               98.5
previous_RATE_INTEREST_PRIMARY_mean            302902               98.5
previous_RATE_INTEREST_PRIMARY_max             302902               98.5
previous_RATE_INTEREST_PRIVILEGED_min          302902               98.5
...                                               ...                ...
EXT_SOURCE_2                                      660                0.2
AMT_GOODS_PRICE                                   278                0.1
AMT_ANNUITY                                        12                0.0
CNT_FAM_MEMBERS                                     2                0.0
DAYS_LAST_PHONE_CHANGE                              1                0.0

[1004 rows x 2 columns]

In [10]:
# Imputing missing values with mean
imputer=SimpleImputer(strategy='mean')
imputer.fit(x)
x=imputer.transform(x)

In [11]:
# Converting inf values to zero
x[x<0]=0

In [12]:
# Feature selection
chi2_features = SelectKBest(chi2, k = 1000) 
X_kbest_features = chi2_features.fit_transform(x, y)

In [13]:
print('Original feature number:', x.shape[1]) 
print('Reduced feature number:', X_kbest_features.shape[1])

Original feature number: 1185
Reduced feature number: 1000

In [14]:
# Splitting data
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=0)

### Deep Learning

In [15]:
x_train=np.array(x_train)
y_train=np.array(y_train)
x_test=np.array(x_test)
y_test=np.array(y_test)

### Deep Neural network with 4 layers

In [16]:
#4 layers with 2 hidden layer and the hidden layer has 80 neurons

In [17]:
model =keras.Sequential([
    keras.layers.Flatten(input_shape=(1185,)),
    keras.layers.Dense(80, activation=tf.nn.relu),
	keras.layers.Dense(80, activation=tf.nn.relu),
    keras.layers.Dense(1, activation=tf.nn.sigmoid),
])

WARNING:tensorflow:From C:\Users\jayak\anaconda3\lib\site-packages\tensorflow\python\ops\init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor

In [18]:
model.compile(optimizer='adam', 
              loss='binary_crossentropy', metrics=['accuracy'])

WARNING:tensorflow:From C:\Users\jayak\anaconda3\lib\site-packages\tensorflow\python\ops\nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

In [19]:
model.fit(x_train, y_train, epochs=50, batch_size=1)

Epoch 1/50
215257/215257 [==============================] - ETA: 0s - loss: 2450.8755 - acc: 0.91 - 616s 3ms/sample - loss: 2450.7503 - acc: 0.9176
Epoch 2/50
215257/215257 [==============================] - 652s 3ms/sample - loss: 52.0023 - acc: 0.9187
Epoch 3/50
215257/215257 [==============================] - 666s 3ms/sample - loss: 2.1739 - acc: 0.9188
Epoch 4/50
215257/215257 [==============================] - 532s 2ms/sample - loss: 0.6771 - acc: 0.9188
Epoch 5/50
215257/215257 [==============================] - 1909s 9ms/sample - loss: 0.2820 - acc: 0.9188
Epoch 6/50
215257/215257 [==============================] - 554s 3ms/sample - loss: 0.2820 - acc: 0.9188
Epoch 7/50
215257/215257 [==============================] - 254s 1ms/sample - loss: 0.2819 - acc: 0.9188
Epoch 8/50
215257/215257 [==============================] - 203s 944us/sample - loss: 0.2819 - acc: 0.9188
Epoch 9/50
215257/215257 [==============================] - 186s 865us/sample - loss: 0.2819 - acc: 0.9188
Epoch 10/50
215257/215257 [==============================] - 195s 906us/sample - loss: 0.2820 - acc: 0.9188
Epoch 11/50
215257/215257 [==============================] - 185s 862us/sample - loss: 0.2819 - acc: 0.9188
Epoch 12/50
215257/215257 [==============================] - 183s 850us/sample - loss: 0.2819 - acc: 0.9188
Epoch 13/50
215257/215257 [==============================] - 181s 843us/sample - loss: 0.2819 - acc: 0.9188
Epoch 14/50
215257/215257 [==============================] - 194s 902us/sample - loss: 0.2819 - acc: 0.9188
Epoch 15/50
215257/215257 [==============================] - 211s 980us/sample - loss: 0.2819 - acc: 0.9188- los
Epoch 16/50
215257/215257 [==============================] - 218s 1ms/sample - loss: 0.2819 - acc: 0.9188
Epoch 17/50
215257/215257 [==============================] - 208s 967us/sample - loss: 0.2819 - acc: 0.9188
Epoch 18/50
215257/215257 [==============================] - 215s 1ms/sample - loss: 0.2819 - acc: 0.9188
Epoch 19/50
215257/215257 [==============================] - 214s 996us/sample - loss: 0.2819 - acc: 0.9188
Epoch 20/50
215257/215257 [==============================] - 207s 962us/sample - loss: 0.2819 - acc: 0.9188
Epoch 21/50
215257/215257 [==============================] - 203s 941us/sample - loss: 0.2819 - acc: 0.9188- loss:  - ETA: 1s - loss: 0.2 - ETA: 0s - loss: 0.2817 -
Epoch 22/50
215257/215257 [==============================] - 189s 876us/sample - loss: 0.2819 - acc: 0.9188
Epoch 23/50
215257/215257 [==============================] - 185s 858us/sample - loss: 0.2819 - acc: 0.9188
Epoch 24/50
215257/215257 [==============================] - 183s 850us/sample - loss: 0.2818 - acc: 0.9188
Epoch 25/50
215257/215257 [==============================] - 184s 855us/sample - loss: 0.2818 - acc: 0.9188
Epoch 26/50
215257/215257 [==============================] - 416s 2ms/sample - loss: 0.2818 - acc: 0.9188
Epoch 27/50
215257/215257 [==============================] - 723s 3ms/sample - loss: 0.2818 - acc: 0.9188
Epoch 28/50
215257/215257 [==============================] - 722s 3ms/sample - loss: 0.2818 - acc: 0.9188
Epoch 29/50
215257/215257 [==============================] - 715s 3ms/sample - loss: 0.2818 - acc: 0.9188
Epoch 30/50
215257/215257 [==============================] - 731s 3ms/sample - loss: 0.2818 - acc: 0.9188
Epoch 31/50
215257/215257 [==============================] - 670s 3ms/sample - loss: 0.2818 - acc: 0.9188
Epoch 32/50
215257/215257 [==============================] - 681s 3ms/sample - loss: 0.2818 - acc: 0.9188
Epoch 33/50
215257/215257 [==============================] - 381s 2ms/sample - loss: 0.2818 - acc: 0.9188
Epoch 34/50
215257/215257 [==============================] - 183s 849us/sample - loss: 0.2818 - acc: 0.9188
Epoch 35/50
215257/215257 [==============================] - 183s 851us/sample - loss: 0.2818 - acc: 0.9188
Epoch 36/50
215257/215257 [==============================] - 183s 852us/sample - loss: 0.2818 - acc: 0.9188- loss: 0.2817 - acc: 0. - ETA: 0s - loss: 0.2818
Epoch 37/50
215257/215257 [==============================] - 184s 854us/sample - loss: 0.2818 - acc: 0.9188
Epoch 38/50
215257/215257 [==============================] - 183s 849us/sample - loss: 0.2818 - acc: 0.9188
Epoch 39/50
215257/215257 [==============================] - 183s 848us/sample - loss: 0.2818 - acc: 0.9188- loss: 0.2818 - acc: 0.
Epoch 40/50
215257/215257 [==============================] - 183s 849us/sample - loss: 0.2818 - acc: 0.9188
Epoch 41/50
215257/215257 [==============================] - 183s 848us/sample - loss: 0.2818 - acc: 0.9188
Epoch 42/50
215257/215257 [==============================] - 183s 852us/sample - loss: 0.2818 - acc: 0.9188
Epoch 43/50
215257/215257 [==============================] - 183s 849us/sample - loss: 0.2818 - acc: 0.9188
Epoch 44/50
215257/215257 [==============================] - 183s 850us/sample - loss: 0.2818 - acc: 0.9188
Epoch 45/50
215257/215257 [==============================] - 183s 848us/sample - loss: 0.2818 - acc: 0.9188
Epoch 46/50
215257/215257 [==============================] - 183s 849us/sample - loss: 0.2818 - acc: 0.9188 ETA
Epoch 47/50
215257/215257 [==============================] - 183s 848us/sample - loss: 0.2818 - acc: 0.9188
Epoch 48/50
215257/215257 [==============================] - 183s 848us/sample - loss: 0.2818 - acc: 0.9188
Epoch 49/50
215257/215257 [==============================] - 182s 847us/sample - loss: 0.2818 - acc: 0.9188
Epoch 50/50
215257/215257 [==============================] - 182s 848us/sample - loss: 0.2818 - acc: 0.9188

In [20]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
flatten (Flatten)            (None, 1185)              0
_________________________________________________________________
dense (Dense)                (None, 80)                94880
_________________________________________________________________
dense_1 (Dense)              (None, 80)                6480
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 81
=================================================================
Total params: 101,441
Trainable params: 101,441
Non-trainable params: 0
_________________________________________________________________

In [21]:
test_loss, test_acc = model.evaluate(x_test,y_test)

print('Test accuracy:', test_acc)

92254/92254 [==============================] - 5s 54us/sample - loss: 0.4278 - acc: 0.9204
Test accuracy: 0.9204262

In [22]:
predictions = model.predict(x_test)

In [23]:
accuracy_score(y_test, predictions.round())

0.9204262145814815

### Deep Neural network with 5 layers

In [24]:
# 5 layers with 3 hidden layers, first and second hidden layer has 80 neurons and third hidden layer has 40 neurons

In [26]:
model =keras.Sequential([
    keras.layers.Flatten(input_shape=(1185,)),
    keras.layers.Dense(80, activation=tf.nn.relu),
    keras.layers.Dense(80, activation=tf.nn.relu),
    keras.layers.Dense(40, activation=tf.nn.relu),
    keras.layers.Dense(1, activation=tf.nn.sigmoid),
])

In [27]:
model.compile(optimizer='adam', 
              loss='binary_crossentropy', metrics=['accuracy'])

In [28]:
model.fit(x_train, y_train, epochs=50, batch_size=1)

Epoch 1/50
215257/215257 [==============================] - 521s 2ms/sample - loss: 1535.9097 - acc: 0.9168
Epoch 2/50
215257/215257 [==============================] - 584s 3ms/sample - loss: 0.2837 - acc: 0.9188
Epoch 3/50
215257/215257 [==============================] - 614s 3ms/sample - loss: 0.2818 - acc: 0.9188
Epoch 4/50
215257/215257 [==============================] - 652s 3ms/sample - loss: 0.2818 - acc: 0.9188
Epoch 5/50
215257/215257 [==============================] - 653s 3ms/sample - loss: 0.2819 - acc: 0.9188
Epoch 6/50
215257/215257 [==============================] - 637s 3ms/sample - loss: 0.2818 - acc: 0.9188
Epoch 7/50
215257/215257 [==============================] - 642s 3ms/sample - loss: 0.2818 - acc: 0.9188
Epoch 8/50
215257/215257 [==============================] - 765s 4ms/sample - loss: 0.2819 - acc: 0.9188
Epoch 9/50
215257/215257 [==============================] - 647s 3ms/sample - loss: 0.2818 - acc: 0.9188
Epoch 10/50
215257/215257 [==============================] - 734s 3ms/sample - loss: 0.2818 - acc: 0.9188
Epoch 11/50
215257/215257 [==============================] - 762s 4ms/sample - loss: 0.2818 - acc: 0.9188
Epoch 12/50
215257/215257 [==============================] - 577s 3ms/sample - loss: 0.2818 - acc: 0.9188
Epoch 13/50
215257/215257 [==============================] - 194s 901us/sample - loss: 0.2818 - acc: 0.9188
Epoch 14/50
215257/215257 [==============================] - 194s 901us/sample - loss: 0.2818 - acc: 0.9188
Epoch 15/50
215257/215257 [==============================] - 194s 901us/sample - loss: 0.2818 - acc: 0.9188
Epoch 16/50
215257/215257 [==============================] - 194s 904us/sample - loss: 0.2818 - acc: 0.9188
Epoch 17/50
215257/215257 [==============================] - 202s 938us/sample - loss: 0.2818 - acc: 0.9188
Epoch 18/50
215257/215257 [==============================] - 208s 964us/sample - loss: 0.2818 - acc: 0.9188
Epoch 19/50
215257/215257 [==============================] - 209s 972us/sample - loss: 0.2818 - acc: 0.9188- loss: 0.28
Epoch 20/50
215257/215257 [==============================] - 200s 931us/sample - loss: 0.2818 - acc: 0.9188
Epoch 21/50
215257/215257 [==============================] - 205s 955us/sample - loss: 0.2818 - acc: 0.9188
Epoch 22/50
215257/215257 [==============================] - 196s 913us/sample - loss: 0.2818 - acc: 0.9188
Epoch 23/50
215257/215257 [==============================] - 201s 932us/sample - loss: 0.2818 - acc: 0.9188- loss: 0.2819 - acc - ETA: 1s - loss: 0. - ETA: 0s - loss: 0.2819 -
Epoch 24/50
215257/215257 [==============================] - 196s 910us/sample - loss: 0.2818 - acc: 0.9188
Epoch 25/50
215257/215257 [==============================] - 200s 928us/sample - loss: 0.2818 - acc: 0.9188
Epoch 26/50
215257/215257 [==============================] - 204s 949us/sample - loss: 0.2818 - acc: 0.9188
Epoch 27/50
215257/215257 [==============================] - 199s 927us/sample - loss: 0.2818 - acc: 0.9188
Epoch 28/50
215257/215257 [==============================] - 205s 951us/sample - loss: 0.2818 - acc: 0.9188
Epoch 29/50
215257/215257 [==============================] - 198s 918us/sample - loss: 0.2818 - acc: 0.9188- loss: 0.281
Epoch 30/50
215257/215257 [==============================] - 201s 935us/sample - loss: 0.2818 - acc: 0.9188
Epoch 31/50
215257/215257 [==============================] - 193s 896us/sample - loss: 0.2818 - acc: 0.9188
Epoch 32/50
215257/215257 [==============================] - 194s 903us/sample - loss: 0.2818 - acc: 0.9188- loss: 0.2816 - acc - ETA - ETA: 1s - loss
Epoch 33/50
215257/215257 [==============================] - 195s 906us/sample - loss: 0.2818 - acc: 0.9188-
Epoch 34/50
215257/215257 [==============================] - 193s 899us/sample - loss: 0.2818 - acc: 0.9188
Epoch 35/50
215257/215257 [==============================] - 194s 900us/sample - loss: 0.2818 - acc: 0.9188
Epoch 36/50
215257/215257 [==============================] - 193s 895us/sample - loss: 0.2818 - acc: 0.9188
Epoch 37/50
215257/215257 [==============================] - 193s 894us/sample - loss: 0.2818 - acc: 0.9188
Epoch 38/50
215257/215257 [==============================] - 193s 896us/sample - loss: 0.2818 - acc: 0.9188
Epoch 39/50
215257/215257 [==============================] - 193s 896us/sample - loss: 0.2818 - acc: 0.9188- loss: 0.2819 - acc - ETA: 0s - loss:
Epoch 40/50
215257/215257 [==============================] - 193s 898us/sample - loss: 0.2818 - acc: 0.9188
Epoch 41/50
215257/215257 [==============================] - 193s 899us/sample - loss: 0.2818 - acc: 0.9188
Epoch 42/50
215257/215257 [==============================] - 193s 895us/sample - loss: 0.2818 - acc: 0.9188- loss: 0.2817 -
Epoch 43/50
215257/215257 [==============================] - 193s 899us/sample - loss: 0.2818 - acc: 0.9188- loss: 0.2818
Epoch 44/50
215257/215257 [==============================] - 194s 900us/sample - loss: 0.2818 - acc: 0.9188
Epoch 45/50
215257/215257 [==============================] - 193s 897us/sample - loss: 0.2818 - acc: 0.9188
Epoch 46/50
215257/215257 [==============================] - 194s 900us/sample - loss: 0.2818 - acc: 0.9188- loss: 0.2817 - acc:
Epoch 47/50
215257/215257 [==============================] - 193s 897us/sample - loss: 0.2818 - acc: 0.9188- loss: 0.2817 - acc - ETA: 3s
Epoch 48/50
215257/215257 [==============================] - 193s 899us/sample - loss: 0.2818 - acc: 0.9188- loss: 0.2819 - acc:
Epoch 49/50
215257/215257 [==============================] - 194s 900us/sample - loss: 0.2818 - acc: 0.9188
Epoch 50/50
215257/215257 [==============================] - 192s 894us/sample - loss: 0.2818 - acc: 0.9188- loss:

In [29]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
flatten_1 (Flatten)          (None, 1185)              0
_________________________________________________________________
dense_3 (Dense)              (None, 80)                94880
_________________________________________________________________
dense_4 (Dense)              (None, 80)                6480
_________________________________________________________________
dense_5 (Dense)              (None, 40)                3240
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 41
=================================================================
Total params: 104,641
Trainable params: 104,641
Non-trainable params: 0
_________________________________________________________________

In [30]:
test_loss, test_acc = model.evaluate(x_test,y_test)

print('Test accuracy:', test_acc)

92254/92254 [==============================] - 4s 46us/sample - loss: 0.2777 - acc: 0.9204
Test accuracy: 0.92043704

In [31]:
predictions = model.predict(x_test)

In [32]:
accuracy_score(y_test, predictions.round())

0.9204370542198712